### PR TITLE
added setting to optionally also block staff users

### PR DESCRIPTION
**Pull request by kakulukia**

### CODE REVIEW

**Comment by kakulukia** [comment]
i didnt test this at first .. but superusers should still be granted access to the site :)

**Comment by kakulukia** [comment]
@alsoicode may you now have some time to release the next version? :)

**Comment by alsoicode** [comment]
I should be able to get a release out today. Looking at it right now.

**Comment by kakulukia** [comment]
cool!

**Comment by alsoicode** [comment]
Version 1.1.10 has been released to PyPi

**Pull request merged**
