### PR TITLE
Bug fix + json support

### PR DESCRIPTION
**Pull request by BrunoDesthuilliers**
1. Fixes a bug with multiple Maintenance being created for the same site (using MySQL), which totally broke the whole site. `Maintenance` instances are now unique per site (s/ForeignKey/OneToOneField) and are only created (if not already existing) when accessing the admin or using the setmaintenance command.  

2. Middleware now returns a json response if request.content_type is 'application/json' so we can have a usable response for REST/json apis 

3. Reordered tests in the middleware to avoid potentially useless db hits (first check request.user status and internal_ips, only then check the site's maintenance instance)

### CODE REVIEW

**Comment by alsoicode** [comment]
Thanks Bruno. I should be able to get this out to PyPi later today.

**Comment by BrunoDesthuilliers** [comment]
Thanks for being so reactive, that's a pleasure :-)

**Comment by alsoicode** [comment]
You're very welcome, and your contributions are always great.

**Comment by alsoicode** [comment]
Released 1.1.9 to PyPi

**Comment by BrunoDesthuilliers** [comment]
thx

**Pull request merged**
